### ISSUE TITLE
Cannot deref a register location description until location descriptions are allowed on the stack

### ISSUE THREAD

**Issue by t-tye** [ccoutant/dwarf-locations#11]
In 001-clarifications-eval.txt line 406 until location descriptions are allowed on the stack you cannot deref a register location description. So this should be moved to 004-locations-on-stack.txt or a separate part after it.

**Comment by ZaricZoran** [comment]
When that is removed, is there a reason to include any change for the DW_OP_regval_type operation?

There doesn't seem to be a need to mention it at this point in the series, or am I missing some subtle but important difference in the definition?

**Comment by ccoutant** [comment]
Moved this to 004.
