### ISSUE TITLE
DW_OP_call* cannot handle location description results until location descriptuions allowed on the stack.

### ISSUE THREAD

**Issue by t-tye** [ccoutant/dwarf-locations#14]
In 001-clarifications-eval.txt lines 671-699, until location descriptions are allowed on the stack it is unclear how DW_OP_call* can return location descriptions meaningfully. So maybe this should move to 004-locations-on-stack.txt .

**Comment by ZaricZoran** [comment]
I had the same though. At this point in the series, we don't need for DW_OP_call to change in any way.

**Comment by ccoutant** [comment]
Moved these two bullets to 004.
