### ISSUE TITLE
Where is section 2.5.4.4.3?

### ISSUE THREAD

**Issue by woodard** [ccoutant/dwarf-locations#3]
There are 3 places where you mention section: 2.5.4.4.3 Memory Location Description Operations in https://github.com/ccoutant/dwarf-locations/blob/main/001-clarifications-eval.txt However this does not exist in the current DWARF5 standard which only goes up to 2.5.1.7 

Neither does it seem to exist in 0001-clarifications-eval.txt and I don't see it in 00[2-6] either and so I do not know where you are referring to.

Since it only seems to be referred to within document 0001, it should probably be part of the text of that file.

**Comment by t-tye** [comment]
The creation of "2.5.4.4.3 Memory Location Description Operations" may be part of the editorial reorganization. So adding the references to it may need to be part of that part.

**Comment by ccoutant** [comment]
Moved these passages to 004.
