### ISSUE TITLE
simplify address space chapter

### ISSUE THREAD

**Issue by markus-metzger** [ccoutant/dwarf-locations#52]
The chapter about address spaces [https://github.com/ccoutant/dwarf-locations/blob/b1d75746e53e1bf090e1c112a7a157f59bf1c550/005-address-spaces.txt] is a very tough read - at least for me.

All we want to say is that there is one or more address space(s) denoted by some ABI-defined integer number with zero denoting the default address space.

Whether this is byte-addressible or using some other unit doesn't really matter, here, does it?  And whether there is memory behind it doesn't matter, either.

What is missing, however, is how the address space is actually represented in DWARF.  The text refers to `DW_ASPACE_none` but doesn't introduce `DW_ASPACE` nor any other means of actually specifying the address space.

**Comment by ccoutant** [comment]
Tony rewrote the address space chapter.
