### ISSUE TITLE
2.5.x.x Implicit Location Description Operations

### ISSUE THREAD

**Issue by woodard** [ccoutant/dwarf-locations#6]
There are several references to “2.5.x.x Implicit Location Description Operations” in 0001 but that section does not yet appear to be finished or is not in Section 2.5. I’m not sure but you may be referring to 2.6.1.1.4 Implicit Location Descriptions which defines the operations that work on implicit location descriptions.

**Comment by t-tye** [comment]
The creation of "2.5.4.4.5 Implicit Location Description Operations" may be part of the editorial reorganization. So adding the references to it may need to be part of that part.

**Comment by ccoutant** [comment]
I've fixed the reference to point to the 2.6.1.1.4 section in the DWARF 5 spec. It'll get updated with the renumbering in 004.
