### ISSUE TITLE
Remove mention of evaluating on a value stack

### ISSUE THREAD

**Issue by t-tye** [ccoutant/dwarf-locations#7]
On 001-clarifications-eval.txt lines 3-4 also need to state that the second sentence of paragraph 1 should be deleted.

"They are expressed in terms of DWARF operations that operate on a stack of values." is no longer true as the stack now has values and location descriptions. Even in DWARF 5 it was not true as location descriptions are not evaluated on the value stack.

**Comment by ccoutant** [comment]
Will remove that sentence as part of 004.
