### ISSUE TITLE
Define operation expression

### ISSUE THREAD

**Issue by t-tye** [ccoutant/dwarf-locations#9]
Add the following paragraph before line 279 of 001-clarifications-eval.txt:

  An operation expression is comprised of a stream of operations, each consisting
  of an opcode followed by zero or more operands. The number of operands is
  implied by the opcode.

This defines the term operation expression and stream.

**Comment by ccoutant** [comment]
Replaced the term "operation expression" with "expression" in 001. We introduce the term "operation expression" in 004.
